apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: {{ .Values.project }}

  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.8.0
    chart: cert-manager
    helm:
      parameters:
      - name: installCRDs
        value: 'true'
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
  destination: 
    server: {{ .Values.cluster }}
    namespace: cert-manager

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true