apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: airflow
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    helm:
      valueFiles:
      - values.yaml
    repoURL: 'https://git.source.akamai.com/scm/dlt/helm-tandav.git'
    targetRevision: develop
    path: airflow-helm-chart/

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
